"""Recipe and ingredient domain models."""

from django.conf import settings
from django.db import models

from core.services.recipe import normalize_flavor_tags


class Recipe(models.Model):
    """Recipe content shared by users or generated by AI."""

    DIFFICULTY_CHOICES = (
        ('easy', 'Easy'),
        ('medium', 'Medium'),
        ('hard', 'Hard'),
    )
    STATUS_PUBLISHED = 'published'
    STATUS_BLOCKED = 'blocked'
    STATUS_CHOICES = (
        (STATUS_PUBLISHED, 'Published'),
        (STATUS_BLOCKED, 'Blocked'),
    )
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    cuisine = models.CharField(max_length=50)
    flavor = models.CharField(max_length=100, blank=True)
    steps = models.JSONField(default=list)
    cooking_time = models.IntegerField(help_text='Minutes')
    difficulty = models.CharField(max_length=20, choices=DIFFICULTY_CHOICES, default='easy')
    nutrition = models.JSONField(default=dict, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='recipes')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=STATUS_PUBLISHED)
    is_ai_generated = models.BooleanField(default=False)
    source_prompt = models.JSONField(default=dict, blank=True)
    view_count = models.IntegerField(default=0)
    search_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['status', 'created_at'], name='recipe_status_created_idx'),
            models.Index(fields=['status', 'view_count', 'search_count'], name='recipe_status_heat_idx'),
            models.Index(fields=['status', 'cuisine'], name='recipe_status_cuisine_idx'),
            models.Index(fields=['status', 'flavor'], name='recipe_status_flavor_idx'),
        ]

    def __str__(self):
        return self.title

    @property
    def flavor_tags(self):
        """Normalize stored flavor text into display-ready tag list."""
        return normalize_flavor_tags(self.flavor)


class Ingredient(models.Model):
    """Single ingredient line belonging to a recipe."""

    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='ingredients')
    name = models.CharField(max_length=100)
    quantity = models.CharField(max_length=50)
    unit = models.CharField(max_length=20)
    alternative = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return f'{self.name} ({self.quantity}{self.unit})'
